version: "3.9"

services:
  flaskapp1:
    build:
      context: ./
    ports:
      - "5000:5000"

  flaskapp2:
    build:
      context: ./
    ports:
      - "5001:5000"

  flaskapp3:
    build:
      context: ./
    ports:
      - "5002:5000"